### ISSUE TITLE
Logo offer for FadeInTextView

### ISSUE THREAD

**Issue by familqasimov** [ChahatGupta/FadeInTextView-Android#1]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/40272138-ed671fdc-5bb9-11e8-92fd-a7157d99f036.png)

Best regard
Famil.

**Comment by chtgupta** [comment]
Hi @familqasimov 
I too wanted to give it a logo but couldn't as I'm not very much into designing yet. I appreciate your concern and would love to get a logo from your side.

You can do one of these things:

- Send me a pull request.

- Hit me up in my [inbox](mailto:admin@believe-labs.co) and I'll add the logo to this repository and the demo app with proper credits.

Cheers!
