### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [ChahatGupta/FadeInTextView-Android#3]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by chtgupta** [comment]
Hey @mansya 
Would love to get a brand new logo for this project by your side.
Before getting your hands in, please do have a look at the previous issues/PRs to get a clear understanding of why I didn't accept the previously offered logos.
Go ahead and fork the repo!

Cheers!

**Comment by mansya** [comment]
ok. I will see that

**Comment by mansya** [comment]
I have designed a logo for this app. What do you think ? do you like it ?

![fade-in textview](https://user-images.githubusercontent.com/33461607/41808666-2a519a32-770b-11e8-932f-707e845860c0.png)

I use 2 letter F it describes that text F is like fade. and I designed the frame shadow behind it to illustrate that this app is a text-based fade app

**Comment by chtgupta** [comment]
Hi @mansya 
I appreciate your concern for this project and I really like the way you try to explain things with your work. Can you please change the Ff with Tt? Also, I would recommend you (not mandatory) for playing around with the dotted lines a bit or just change them with solid ones. This is somewhat the kind of logo I've been wishing for this repo. I like the blue ones especially.

**Comment by mansya** [comment]
I have changed it with the letters Tt. and I have also changed the frame. I create a frame like that for the logo to look unique and interesting. What do you think ?
![fade-in textview](https://user-images.githubusercontent.com/33461607/41810447-a4c42542-7728-11e8-9f5d-dd19a46ef520.png)

**Comment by chtgupta** [comment]
This looks perfect to me!
Go ahead and fork the repo, implement changes and send me a PR. Great work!

**Comment by mansya** [comment]
I have uploaded all files to this link.
https://drive.google.com/open?id=1o6nbcCKKyyi6t0fJN-QtC-gF7CDm8PKG

and I have sent you Pull Requests. Please check

**Comment by chtgupta** [comment]
The PR has been merged. Will add the logo in the app soon.
